# .pre-commit-config.yaml
# ========================
#
# pre-commit clean
# pre-commit install
# pre-commit install-hooks
#
# precommit hooks installation
#
# - pre-commit autoupdate
#
# - pre-commit run black
#
# continuous integration
# ======================
#
# - pre-commit run --all-files

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: 8fe62d14e0b4d7d845a7022c5c2c3ae41bdd3f26  # frozen: v4.1.0
  hooks:
  - id: check-added-large-files
  - id: check-ast
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-json
  - id: pretty-format-json
    args: ['--autofix', '--no-ensure-ascii']
    exclude: Pipfile.lock|cdk.json
  - id: debug-statements
  - id: mixed-line-ending
    args: ['--fix=lf']
  - id: name-tests-test
    args: ['--django']

- repo: https://github.com/Yelp/detect-secrets
  rev: f6027a0521e044ba46e54611cabd787b7a88d1a9  # frozen: v1.1.0
  hooks:
  - id: detect-secrets
    exclude: .pre-commit-config.yaml

- repo: https://github.com/psf/black
  rev: fc0be6eb1e2a96091e6f64009ee5e9081bf8b6c6  # frozen: 22.1.0
  hooks:
  - id: black
    language_version: python3.9

- repo: https://github.com/asottile/blacken-docs
  rev: 7ae9389351f4090e3993de28015a05a18ca6b8a7  # frozen: v1.12.1
  hooks:
  - id: blacken-docs

- repo: https://github.com/asottile/reorder_python_imports
  rev: 15ae07db4568a7d71591f3e588afa6e22ca2efe7  # frozen: v2.7.1
  hooks:
  - id: reorder-python-imports
