# .pre-commit-config.yaml
# ========================
#
# pre-commit clean
# pre-commit install
# pre-commit install-hooks
#
# precommit hooks installation
#
# - pre-commit autoupdate
#
# - pre-commit run black
#
# continuous integration
# ======================
#
# - pre-commit run --all-files

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
  - id: check-added-large-files
  - id: check-ast
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-json
  - id: pretty-format-json
    args: ['--autofix', '--no-ensure-ascii']
    exclude: Pipfile.lock|cdk.json
  - id: debug-statements
  - id: mixed-line-ending
    args: ['--fix=lf']
  - id: name-tests-test
    args: ['--django']

- repo: https://github.com/Yelp/detect-secrets
  rev: v1.2.0
  hooks:
  - id: detect-secrets
    exclude: .pre-commit-config.yaml

- repo: https://github.com/asottile/reorder_python_imports
  rev: v3.8.1
  hooks:
  - id: reorder-python-imports

- repo: https://github.com/psf/black
  rev: 22.6.0
  hooks:
  - id: black
    language_version: python3.9

- repo: https://github.com/asottile/blacken-docs
  rev: v1.12.1
  hooks:
  - id: blacken-docs

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: 'v0.961'
  hooks:
  - id: mypy
    additional_dependencies:
    - "types-requests"
    - "boto3-stubs[s3]"
